[project]
name = "morphopt"
version = "3.1.5"
description = "A morphing optimization framework using PyTorch and Abaqus."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.0.0",
    "torchvision>=0.15.1",
    "numpy>=2.0.0",
    "pypardiso>=0.4.7",
    "pyqt6>=6.11.0",
    "pyvista>=0.47.1",
    "pyvistaqt>=0.11.3",
    "vtk>=9.6.1",
    "gmsh>=4.15.0",
    "tabulate>=0.9.0",
    "imageio>=2.37.3",
    "bspmap>=1.0.3",
    "torchfea>=1.0.12",
    "trimesh>=4.11.5",
    "networkx>=3.6.1",
    "scipy>=1.17.1",
    "cpgeo>=1.0.11",
]
